### ISSUE TITLE
不能区分左右 Shift 键

### ISSUE THREAD

**Issue by BillLeecn** [osfans/PRIME#3]
希望使用左右 shift 选择第 2, 3 候选字。配置文件 `luna_pinyin.custom.yaml`:

```yaml
patch:
  key_binder/import_preset: default
  key_binder/bindings:
    - { when: composing, accept: "Shift_L", send: 2 }
    - { when: composing, accept: "Shift_R", send: 3 }
```

以前的鼠须管用的是 `Shift+Shift_L`, `Shift+Shift_R`, 不起作用，换成上面这个配置后，发现左右 shift 不能区分，如果第一次按的是左 shift, 那么接下来的右 shift 也会选择第 2 候选字; 反之亦然。
