### ISSUE TITLE
横排模式下候选词之间距离有问题

### ISSUE THREAD

**Issue by lizyn** [osfans/PRIME#5]
如图所示：
![image](https://cloud.githubusercontent.com/assets/26119970/23834303/4d97d6f6-078f-11e7-95e0-4e301e87843a.png)

刚安装试用，只在用户文件夹中增加了这两个文件后重新部署，win 10 系统
1. default.custom.yaml
```
patch:
  menu:
    page_size: 7
```
2. PIME.custom.yaml
```
patch:
  style:
    color_scheme: dark_temple
    font_face: "Microsoft YaHei"
    font_point: 12
    inline_preedit: composition #composition, preview, input, false
    display_tray_icon: true
    candidate_format: "{0} {1}" #0-candidate, 1-comment
    horizontal: true
    candidate_per_row: 1
    candidate_use_cursor: true
    sel_key_use_cursor: true
    desktop_use_3d_border: false
    soft_cursor: false
    menu_opencc: "" #tw2s.json, t2s.json
    layout:
      min_width: 160
      min_height: 0
      border_width: 3
      margin_x: 12
      margin_y: 12
      spacing: 10
      candidate_spacing: 5
      hilite_spacing: 4
      hilite_padding: 2
      round_corner: 4
      position: "left"
```
